#cloud-config
package_update: true
write_files:
  - path: /tmp/lb.sh
    content: |
      #!/usr/bin/env

      set -e -u -x

      apt install -y qemu-guest-agent
      systemctl start qemu-guest-agent

      apt-get update
      apt-get upgrade -y
      apt-get install -y haproxy

    permissions: '0755'
runcmd:
 - [sh, "/tmp/lb.sh"]
