---
kubeProxyReplacement: true
ingressController:
  enabled: true
  loadbalancerMode: shared
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443
k8sServiceHost: 192.168.1.130
k8sServicePort: 6443
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - httpV2
  relay:
    enabled: true
  ui:
    enabled: true
encryption:
  enabled: true
  type: wireguard
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
#ipam:
#  operator:
#    clusterPoolIPv4PodCIDRList: "10.42.0.0/16"
